language: php
php:
  - "5.5"

before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - phpunit -v

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false